name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - name: Install Cross Compilation Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib gcc-mingw-w64 gcc-aarch64-linux-gnu
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1
          CC_FOR_TARGET_linux_amd64: x86_64-linux-gnu-gcc
          CC_FOR_TARGET_linux_arm64: aarch64-linux-gnu-gcc
          CC_FOR_TARGET_windows_amd64: x86_64-w64-mingw32-gcc
          CC_FOR_TARGET_windows_arm64: aarch64-w64-mingw32-gcc
